name: Pull Request
description: Template for creating pull requests
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Please provide a brief description of the changes and their purpose here.
    validations:
      required: true

  - type: dropdown
    id: release_versioning
    attributes:
      label: ⚠️ RELEASE VERSIONING - REQUIRED ⚠️
      description: Please select ONE of the following options. This determines how the version will be incremented when this PR is merged.
      options:
        - FIX - Patch version increment (e.g., 1.2.3.4 → 1.2.3.5)
        - FEATURE - Minor version increment (e.g., 1.2.3.4 → 1.2.4.0)
        - MAJOR - Major version increment (e.g., 1.2.3.4 → 1.3.0.0). All services will be retagged with the new major version.
        - SKIP - Skip versioning and release creation for this PR
    validations:
      required: true

  - type: textarea
    id: how_to_test
    attributes:
      label: How to test
      description: Description for the reviewer of how to test the changes
    validations:
      required: false

  - type: dropdown
    id: customer_impact
    attributes:
      label: Customer Impact
      description: Please indicate the level of customer impact for this change
      options:
        - Low - Minimal impact, no noticeable change to customers
        - Medium - Some impact, might have visual impact or impact on request quality
        - High - Significant impact, might render the software unusable
    validations:
      required: false

  - type: checkboxes
    id: pr_checklist
    attributes:
      label: Checklist for PR
      options:
        - label: I have manually tested the changes
        - label: Integration tests have been added
        - label: Security-considerations have been made
        - label: Documentation has been updated (if applicable)
        - label: Relevant stakeholders have been notified (if applicable)

  - type: textarea
    id: security_questions
    attributes:
      label: Security-Related Questions
      description: |
        - Was a new package added?
        - Was a new route added?
        - Were any other security-relevant parts of the software changed (e.g., new port, authentication)?
    validations:
      required: false

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots (if applicable)
      description: Please attach any relevant screenshots to illustrate the changes.
    validations:
      required: false

  - type: textarea
    id: additional_notes
    attributes:
      label: Additional Notes
      description: Please add any additional information that might be useful for reviewers.
    validations:
      required: false

