name: "Bug Report"
description: "Report a bug or unexpected behavior in the application."
title: "[Bug]: "
labels: ["bug"]
assignees: ["HajekTim"]

body:
  - type: markdown
    attributes:
      value: |
        ## Bug Report
        Please fill out the information below to help us understand the issue.

  - type: textarea
    id: bug_description
    attributes:
      label: "Describe the bug"
      description: "Provide a clear and concise description of what the bug is."
      placeholder: "A clear and concise description of what the bug is."
      validations:
        required: true

  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: "Steps to reproduce"
      description: "Describe the steps to reproduce the behavior."
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
      validations:
        required: true

  - type: textarea
    id: expected_behavior
    attributes:
      label: "Expected behavior"
      description: "A clear and concise description of what you expected to happen."
      placeholder: "What was the expected outcome?"
      validations:
        required: true

  - type: input
    id: screenshots
    attributes:
      label: "Screenshots"
      description: "If applicable, provide a link to screenshots that help explain your problem."
      placeholder: "Provide screenshot URLs or remove if not applicable."

  - type: dropdown
    id: environment
    attributes:
      label: "Environment (Desktop)"
      description: "Complete this section if the bug occurred on a desktop environment."
      options:
        - "Not applicable"
        - "Windows"
        - "macOS"
        - "Linux"
        - "Other"
        
  - type: input
    id: desktop_browser
    attributes:
      label: "Desktop Browser"
      description: "If relevant, specify the browser and version (e.g., Chrome 93)."
      placeholder: "e.g., Chrome 93"

  - type: dropdown
    id: smartphone_device
    attributes:
      label: "Environment (Smartphone)"
      description: "Complete this section if the bug occurred on a smartphone."
      options:
        - "Not applicable"
        - "iPhone"
        - "Android Phone"
        - "Other"

  - type: input
    id: smartphone_browser
    attributes:
      label: "Smartphone Browser"
      description: "If relevant, specify the browser and version (e.g., Safari 14)."
      placeholder: "e.g., Safari 14"

  - type: textarea
    id: additional_context
    attributes:
      label: "Additional context"
      description: "Add any other context about the problem here."
      placeholder: "Additional information or context."
